apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Category
  formSchema:
    - $formkit: "color"
      name: "color"
      label: "Display Color"
      help: "Front-end Color for the Category Block"
---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "attachment"
      name: "icon"
      label: "Link Icon in the index page"
      help: "Front-end link icon for tag in index page"
---