apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-luna-setting
spec:
  forms:
    - group: layout
      label: layout
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: post list layout
          value: single
          options:
            - label: single
              value: single
            - label: Grid (one row and two columns)
              value: grid_2
            - label: Grid (one row and three columns)
              value: grid_3
          help: "When selecting a single article, the image of the article card will be on the left"
        - $formkit: radio
          name: content_header
          label: Image at top of article page
          value: false
          options:
            - label: display
              value: true
            - label: hide
              value: false
        - $formkit: radio
          name: hide_avatar
          id: hide_avatar
          key: hide_avatar
          label: Hide author avatar
          value: false
          options:
            - label: Hide
              value: true
            - label: Display
              value: false
        - $formkit: radio
          name: hide_author
          id: hide_author
          key: hide_author
          label: Hide author name
          value: false
          options:
            - label: Hide
              value: true
            - label: Display
              value: false
        - $formkit: text
          if: "$get(hide_author).value === false"
          name: common_author
          label: Unify author name
          help: "Empty to display original article author"

    - group: banner
      label: Banner
      formSchema:
        - $formkit: text
          name: custom_title
          label: Banner Title
        - $formkit: text
          name: custom_sub_title
          label: Banner Sub Title
        - $formkit: select
          name: header_background_type
          id: header_background_type
          key: header_background_type
          label: Banner Background
          value: image
          options:
            - label: manual setting
              value: manual
            - label: Image
              value: image
            - label: Video
              value: video
        - $formkit: text
          if: "$get(header_background_type).value === manual"
          name: header_background
          id: header_background
          key: header_background
          label: Banner BG Color
          help: "Fill in the hexadecimal color"
        - $formkit: attachment
          if: "$get(header_background_type).value === image"
          name: header_background_image_1
          id: header_background_image_1
          key: header_background_image_1
          label: Banner BG Image 1
          value: "/themes/theme-Luna/assets/images/default-background.png"

        - $formkit: attachment
          if: "$get(header_background_type).value === image"
          name: header_background_image_2
          id: header_background_image_2
          key: header_background_image_2
          label: Banner BG Image 2
          value: "/themes/theme-Luna/assets/images/default-background.png"

        - $formkit: attachment
          if: "$get(header_background_type).value === image"
          name: header_background_image_3
          id: header_background_image_3
          key: header_background_image_3
          label: Banner BG Image 3
          value: "/themes/theme-Luna/assets/images/default-background.png"

        - $formkit: attachment
          if: "$get(header_background_type).value === 'video'"
          name: header_background_video
          id: header_background_video
          key: header_background_video
          label: Banner BG video URL
          value: /themes/theme-Luna/assets/images/banner.mp4
        - $formkit: radio
          name: search_method
          value: page
          label: Search Method
          options:
            - label: Page
              value: page
            - label: Popup
              value: popup
            - label: None
              value: none
        - $formkit: tagCheckbox
          name: tags
          id: tags
          key: tags
          label: Popular queries
          help: "Select more than three tags and automatically hide excess tags"
                
    - group: index
      label: Index
      formSchema:
        - $formkit: radio
          name: index_menu
          id: index_menu
          key: index_menu
          label: Whether to display module one
          value: false
          options:
            - label: Display
              value: true
            - label: Hide
              value: false
        - $formkit: text
          if: "$get(index_menu).value === true"
          name: module_one
          id: module_one
          key: module_one
          value: module one
          label: name of module one
          help: The first four categories are displayed by default
        - $formkit: select
          if: "$get(index_menu).value === true"
          name: module_one_layout
          label: module one layout
          value: 4
          options:
            - label: Grid (one row and three columns)
              value: 3
            - label: Grid (one row and four columns)
              value: 4
            - label: Grid (one row and five columns)
              value: 5
          help: By default, one row and four columns are displayed.
        - $formkit: radio
          name: index_theme
          id: index_theme
          key: index_theme
          label: Whether to display module two
          value: false
          options:
            - label: Display
              value: true
            - label: Hide
              value: false
        - $formkit: text
          if: "$get(index_theme).value === true"
          name: module_two
          id: module_two
          key: module_two
          value: Module Two
          label: Name of Module Two
        - $formkit: menuRadio
          if: "$get(index_theme).value === true"
          name: menu
          id: menu
          key: menu
          label: Module Two Data Source
          help: The first four first-level menu items are displayed by default
        - $formkit: radio
          name: index_tag
          id: index_tag
          key: index_tag
          label: Whether to display module three
          value: false
          options:
            - label: Display
              value: true
            - label: Hide
              value: false
        - $formkit: text
          if: "$get(index_tag).value === true"
          name: module_there
          id: module_there
          key: module_there
          value: module three
          label: name of module three
        - $formkit: select
          if: "$get(index_tag).value === true"
          name: index_recommend
          id: index_recommend
          key: index_recommend
          label: type of module three 
          value: tag
          options:
            - label: tags
              value: tag
            - label: category
              value: categories
        - $formkit: tagSelect
          if: "$get(index_tag).value === true && $get(index_recommend).value === tag"
          name: tag
          id: tag
          key: tag
          label: module three data source
          help: The first six articles of the selected tag are displayed by default
        - $formkit: categorySelect
          if: "$get(index_tag).value === true && $get(index_recommend).value === categories"
          name: category
          id: category
          key: category
          label: modele three data source 
          help: The first six articles in the selected category are displayed by default.
    - group: style
      label: style
      formSchema:
        - $formkit: radio
          name: color_scheme
          label: Default color
          value: light
          options:
            - label: Dark
              value: dark
            - label: light
              value: light
        - $formkit: attachment
          name: dark_logo
          id: dark_logo
          key: dark_logo
          label: Dark Logo
          help: Use site logo by default
        - $formkit: attachment
          name: light_logo
          id: light_logo
          key: light_logo
          label: Light Logo
          help: Use site logo by default
        - $formkit: checkbox
          name: enable_change_color_scheme
          label: Allow visitors to switch colors
          value: true

        - $formkit: radio
          name: login_info
          id: login_info
          key: login_info
          label: Show login information
          value: false
          options:
            - label: Display
              value: true
            - label: Hide
              value: false
              
        - $formkit: radio
          if: "$get(login_info).value === true"
          name: show_content
          label: Display Content
          value: all
          options:
            - label: Avatar and name
              value: all
            - label: Avatar
              value: avatar
            - label: name
              value: user-name

    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: repeater
          name: widgets
          label: 小部件
          value:
            - value: categories
            - value: tags
          children:
            - $formkit: select
              name: value
              label: 部件
              options:
                - label: 站点资料
                  value: profile
                - label: 热门文章
                  value: popular-posts
                - label: 文章分类
                  value: categories
                - label: 文章标签
                  value: tags

        - $formkit: group
          name: profile
          value:
            logo:
          children:
            - $formkit: attachment
              name: logo
              label: 站点资料 Logo

        - $formkit: repeater
          name: social_media
          label: 社交媒体
          value: []
          children:
            - $formkit: select
              name: icon
              label: 图标
              options:
                - label: 电子邮箱
                  value: i-tabler-mail
                - label: 微信
                  value: i-simple-icons-wechat
                - label: 腾讯 QQ
                  value: i-simple-icons-tencentqq
                - label: 新浪微博
                  value: i-simple-icons-sinaweibo
                - label: 知乎
                  value: i-simple-icons-zhihu
                - label: 豆瓣
                  value: i-simple-icons-douban
                - label: 哔哩哔哩
                  value: i-simple-icons-bilibili
                - label: 抖音 / TikTok
                  value: i-simple-icons-tiktok
                - label: Telegram
                  value: i-simple-icons-telegram
                - label: Facebook
                  value: i-simple-icons-facebook
                - label: Instagram
                  value: i-simple-icons-instagram
                - label: LinkedIn
                  value: i-simple-icons-linkedin
                - label: Twitter
                  value: i-simple-icons-twitter
                - label: Slack
                  value: i-simple-icons-slack
                - label: Discord
                  value: i-simple-icons-discord
                - label: YouTube
                  value: i-simple-icons-youtube
                - label: Steam
                  value: i-simple-icons-steam
                - label: GitHub
                  value: i-simple-icons-github
                - label: GitLab
                  value: i-simple-icons-gitlab
            - $formkit: text
              name: name
              label: 名称
            - $formkit: text
              name: url
              label: 链接
              validation: "required"
            - $formkit: radio
              name: url_type
              label: 链接类型
              value: normal
              help: "如果选择了图片类型，那么在访客点击之后会使用弹框的形式加载"
              options:
                - label: 跳转链接
                  value: normal
                - label: 图片
                  value: image

    - group: footer
      label: 页脚
      formSchema:
        - $formkit: select
          name: style
          id: style
          key: style
          label: 页脚风格
          value: style_1
          options:
            - label: 风格一
              value: style_1
            - label: 风格二
              value: style_2
            - label: 风格三
              value: style_3
            - label: 风格四
              value: style_4
        - $formkit: attachment
          name: logo
          label: Logo
          help: 如果不设置，将使用站点设置的 Logo

        - $formkit: text
          name: title
          label: 标题
          help: 如果不设置，将使用站点设置的标题

        - $formkit: textarea
          rows: 3
          name: slogan
          id: slogan
          key: slogan
          if: "$get(style).value !== style_3"
          label: 标语

        - $formkit: menuRadio
          if: "$get(style).value === style_3"
          name: menu
          id: menu
          key: menu
          label: 右侧菜单

        - $formkit: repeater
          if: "$get(style).value !== style_3"
          name: menus
          id: menus
          key: menus
          label: 菜单组
          value: []
          children:
            - $formkit: menuRadio
              name: name
              label: 菜单
              validation: "required"
              
        - $formkit: attachment
          if: "$get(style).value === style_4"
          name: qrcode
          label: Qrcode
          help: 关注二维码

        - $formkit: repeater
          name: social_media
          label: 社交媒体
          value: []
          children:
            - $formkit: select
              name: icon
              label: 图标
              options:
                - label: 电子邮箱
                  value: i-tabler-mail
                - label: 微信
                  value: i-simple-icons-wechat
                - label: 腾讯 QQ
                  value: i-simple-icons-tencentqq
                - label: 新浪微博
                  value: i-simple-icons-sinaweibo
                - label: 知乎
                  value: i-simple-icons-zhihu
                - label: 豆瓣
                  value: i-simple-icons-douban
                - label: 哔哩哔哩
                  value: i-simple-icons-bilibili
                - label: 抖音 / TikTok
                  value: i-simple-icons-tiktok
                - label: Telegram
                  value: i-simple-icons-telegram
                - label: Facebook
                  value: i-simple-icons-facebook
                - label: Instagram
                  value: i-simple-icons-instagram
                - label: LinkedIn
                  value: i-simple-icons-linkedin
                - label: Twitter
                  value: i-simple-icons-twitter
                - label: Slack
                  value: i-simple-icons-slack
                - label: Discord
                  value: i-simple-icons-discord
                - label: YouTube
                  value: i-simple-icons-youtube
                - label: Steam
                  value: i-simple-icons-steam
                - label: GitHub
                  value: i-simple-icons-github
                - label: GitLab
                  value: i-simple-icons-gitlab
            - $formkit: text
              name: name
              label: 名称
            - $formkit: text
              name: url
              label: 链接
              validation: "required"
            - $formkit: radio
              name: url_type
              label: 链接类型
              value: normal
              help: "如果选择了图片类型，那么在访客点击之后会使用弹框的形式加载"
              options:
                - label: 跳转链接
                  value: normal
                - label: 图片
                  value: image

    - group: contact
      label: Contact
      formSchema:
        - $formkit: radio
          name: enable_whatsapp
          id: enable_whatsapp
          key: enable_whatsapp
          label: Do you wanna enable whatsapp support?
          value: false
          options:
            - label: Yes, I would like to 
              value: true
            - label: No, I don't need
              value: false
        - $formkit: text
          name: whatsapp_number
          id: whatsapp_number
          key: whatsapp_number
          if: "$get(enable_whatsapp).value === true"
          label: WhatsApp Number
          help: "Enter your full WhatsApp number with country code."
          value: 

